"""create books table

Revision ID: 157b5db398a5
Revises: 
Create Date: 2024-07-16 23:18:47.678424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157b5db398a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('published_date', sa.String(length=20), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
